name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ci-${{ github.head_ref }}-pr

jobs:
  administration:
    runs-on: ubuntu-latest
    steps:
      - name: PR Labeling
        uses: srvaroa/labeler@v1.6.1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Test Directory
        run: mkdir -p test-results
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          configuration: './phpunit.xml'
          log_junit: "test-results/phpunit.xml"
          memory_limit: "-1"
          test_suffix: "Test.php"
        env:
          XDEBUG_MODE: coverage
      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action@v2.7.0
        if: ${{ !cancelled() }}
        with:
          files: |
            test-results/phpunit.xml
          check_name: Test Results
          comment_title: Test Results
